services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Database__MigrateOnStartup: "true"
      ConnectionStrings__AdventureDb: Host=postgres;Database=adventure;Username=postgres;Password=${POSTGRES_PASSWORD};SSL Mode=Disable;
      AzureAI__ApiKey: ${AZURE_AI_API_KEY}
      AzureAI__Endpoint: ${AZURE_AI_ENDPOINT}
      AzureStorage__ConnectionString: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
    depends_on:
      postgres:
        condition: service_healthy
      azurite:
        condition: service_started

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: adventure
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
     test: ["CMD-SHELL", "pg_isready -U postgres -d adventure"]
     interval: 5s
     timeout: 5s
     retries: 10
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite
    command: azurite-blob --blobHost 0.0.0.0 --skipApiVersionCheck
    volumes:
      - ./azurite-data:/data

volumes:
  postgres-data:
  azurite-data: