namespace AI.SpectrumAdventure.Infrastructure.Persistence;

/// <summary>The EF Core row backing a persisted Game aggregate; the aggregate itself is stored as a JSON snapshot
/// (research.md Decision 1) rather than fully relational-mapped, keeping the rich Domain graph out of Infrastructure's concern.</summary>
public sealed class GameRecord
{
    public Guid Id { get; set; }

    public required string Json { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset UpdatedAt { get; set; }

    /// <summary>Optimistic concurrency token (research.md Decision 7); regenerated by the repository on every save.</summary>
    public Guid ConcurrencyToken { get; set; }
}
