<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AI.SpectrumAdventure.Domain\AI.SpectrumAdventure.Domain.csproj" />
    <ProjectReference Include="..\AI.SpectrumAdventure.Contracts\AI.SpectrumAdventure.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
